import { expect, test } from '@playwright/test';

test('story-vibepro-evidence-user-fingerprint evidence binding replay', async () => {
  expect('Verification evidence records a user dirty fingerprint that excludes .vibepro and .worktrees/vibepro', 'story-vibepro-evidence-user-fingerprint ac:1 Verification evidence records a user dirty fingerprint that excludes .vibepro and .worktrees/vibepro').toContain('user dirty fingerprint');
  expect('Agent Review records and status checks use the same user dirty fingerprint', 'story-vibepro-evidence-user-fingerprint ac:2 Agent Review records and status checks use the same user dirty fingerprint').toContain('user dirty fingerprint');
  expect('pr prepare compares user dirty fingerprints when both recorded and current contexts provide them', 'story-vibepro-evidence-user-fingerprint ac:3 pr prepare compares user dirty fingerprints when both recorded and current contexts provide them').toContain('compares');
  expect('Legacy evidence that lacks the user fingerprint still uses the existing full dirty fingerprint comparison', 'story-vibepro-evidence-user-fingerprint ac:4 Legacy evidence that lacks the user fingerprint still uses the existing full dirty fingerprint comparison').toContain('Legacy');
  expect('pr prepare reports VibePro-internal dirty files separately from user dirty files', 'story-vibepro-evidence-user-fingerprint ac:5 pr prepare reports VibePro-internal dirty files separately from user dirty files').toContain('separately');
  expect('Managed worktree dirty fingerprinting uses the user scope while retaining raw dirty diagnostics', 'story-vibepro-evidence-user-fingerprint ac:6 Managed worktree dirty fingerprinting uses the user scope while retaining raw dirty diagnostics').toContain('user scope');
  expect('Concurrent review lifecycle starts preserve all lifecycle entries through the existing lock and atomic write path', 'story-vibepro-evidence-user-fingerprint ac:7 Concurrent review lifecycle starts preserve all lifecycle entries through the existing lock and atomic write path').toContain('preserve');
  expect('Given the PR evidence workflow is in a current recorded state for the current HEAD, when tracked VibePro workbench artifacts change, then evidence binding uses the user dirty fingerprint and transitions to PR-ready current while raw dirty diagnostics are still reported', 'story-vibepro-evidence-user-fingerprint S-001 Given the PR evidence workflow is in a current recorded state for the current HEAD, when tracked VibePro workbench artifacts change, then evidence binding uses the user dirty fingerprint and transitions to PR-ready current while raw dirty diagnostics are still reported').toContain('PR-ready current');
  expect('Given the PR evidence workflow is in a legacy full-fingerprint state, when tracked VibePro artifacts change, then VibePro keeps the legacy evidence stale instead of fabricating a user fingerprint transition', 'story-vibepro-evidence-user-fingerprint S-002 Given the PR evidence workflow is in a legacy full-fingerprint state, when tracked VibePro artifacts change, then VibePro keeps the legacy evidence stale instead of fabricating a user fingerprint transition').toContain('legacy');
  expect('Given the Flow Verification workflow is in connection setup state with BASIC_AUTH_USER and BASIC_AUTH_PASSWORD, when evidence git context is recorded, then the Basic Auth connection branch remains unchanged while the user dirty fingerprint is added to the recorded state', 'story-vibepro-evidence-user-fingerprint S-003 Given the Flow Verification workflow is in connection setup state with BASIC_AUTH_USER and BASIC_AUTH_PASSWORD, when evidence git context is recorded, then the Basic Auth connection branch remains unchanged while the user dirty fingerprint is added to the recorded state').toContain('Basic Auth');
});
